combine sliding_48GeV_cat01.root  -M MultiDimFit --algo grid -t -1 --setParameters r=0.5 --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 -n ExpDefault
combine sliding_48GeV_cat01.root  -M MultiDimFit --algo grid --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 -n ObsDefault
combine sliding_48GeV_cat01.root  -M MultiDimFit --algo grid --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 -n ObsPdfIndex0Frozen
combine sliding_48GeV_cat01.root  -M MultiDimFit --algo grid --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV,pdfindex_UntaggedTag_1_2018_13TeV --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 -n ObsPdfIndex01Frozen
#combine m48_cat01.root  -M MultiDimFit --algo grid -t -1 --setParameters r=0.5 --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH,allConstrainedNuisances --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 -n AllConstrainedNuisances
#combine m48_cat01.root  -M MultiDimFit --algo grid -t -1 --setParameters r=0.5 --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 --freezeNuisanceGroups=theory  -n Theory
#combine m48_cat01.root  -M MultiDimFit --algo grid -t -1 --setParameters r=0.5 --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 --freezeNuisanceGroups=exp  -n Experimental
#combine m48_cat01.root  -M MultiDimFit --algo grid -t -1 --setParameters r=0.5 --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH,allConstrainedNuisances,rgx{model_UntaggedTag.*} --X-rtd MINIMIZER_freezeDisassociatedParams  --cminDefaultMinimizerStrategy 0 -n ShapeBkg
#combine m48_cat01.root  -M MultiDimFit --algo grid -t -1 --setParameters r=0.5 --points 1000 --setParameterRanges r=-3,3 -m 48 --freezeParameters MH,allConstrainedNuisances,rgx{model_UntaggedTag.*} --X-rtd MINIMIZER_freezeDisassociatedParams --freezeNuisanceGroups=theory,exp --cminDefaultMinimizerStrategy 0 -n All
