python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 10
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 15
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 20
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 25
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 30
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 35
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 40
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 45
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 50
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 55
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 60
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 65
python3 usingParametricNN_nearestPoint_sigSystAllTrees.py --m 70
