python3 createNewTrees_all4Cat.py  --m 70
python3 createNewTrees_all4Cat.py  --m 65
python3 createNewTrees_all4Cat.py  --m 60
python3 createNewTrees_all4Cat.py  --m 55
python3 createNewTrees_all4Cat.py  --m 50
python3 createNewTrees_all4Cat.py  --m 45
python3 createNewTrees_all4Cat.py  --m 40
python3 createNewTrees_all4Cat.py  --m 35
python3 createNewTrees_all4Cat.py  --m 30
python3 createNewTrees_all4Cat.py  --m 25
python3 createNewTrees_all4Cat.py  --m 20
python3 createNewTrees_all4Cat.py  --m 15
python3 createNewTrees_all4Cat.py  --m 10
